openapi: 3.0.3
info:
  title: StudyStreak PHP backend API
  version: "1.0.0"
  description: >-
    Contract for StudyStreak backend endpoints including todos, gamification,
    and learning material uploads consumed by the StudyStreak frontend.
tags:
  - name: Todos
    description: Manage user todo items.
  - name: Gamification
    description: Track streaks, XP, and profile-level gamification data.
  - name: Learning Materials
    description: Upload, list, and manage shared study resources.
servers:
  - url: https://studystreak-backend.onrender.com
    description: Production deployment
  - url: http://localhost:8181
    description: Local development server
paths:
  /api/todos:
    get:
      tags:
        - Todos
      summary: List todos
      description: >-
        Returns a list of todos. Optional `user_id` query parameter filters the
        result set by owner.
      parameters:
        - in: query
          name: user_id
          schema:
            type: integer
          description: Filter todos by owner id
      responses:
        '200':
          description: Successful response containing a JSON array of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized – missing or invalid bearer token
    post:
      tags:
        - Todos
      summary: Create a todo
      description: >-
        Create a new todo. Requires an `Authorization: Bearer <user_jwt>` header
        with a valid Supabase user JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Created – returns the newly created todo representation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized – missing or invalid bearer token
  /api/gamification/profile:
    get:
      tags:
        - Gamification
      summary: Current user gamification profile
      description: >-
        Fetches the authenticated user's gamification stats (level, streak,
        experience points) from the Supabase `profiles` table.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Gamification profile for the signed-in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamificationProfile'
        '401':
          description: Unauthorized – missing or invalid bearer token
        '404':
          description: Profile not found
  /api/gamification/streak/activate:
    post:
      tags:
        - Gamification
      summary: Record a study activity and update streak
      description: >-
        Marks the authenticated user's streak as active for the supplied
        activity time. The backend will increment or reset the streak based on
        the user's previous activity and timezone, update the longest streak,
        and optionally add to the tracked study minutes.
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GamificationStreakActivationRequest'
      responses:
        '200':
          description: Updated streak state along with the latest profile summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamificationStreakActivationResponse'
        '400':
          description: Invalid payload
        '401':
          description: Unauthorized – missing or invalid bearer token
        '404':
          description: Profile not found
  /api/gamification/set-timezone:
    post:
      tags:
        - Gamification
      summary: Update streak timezone
      description: >-
        Updates the authenticated user's preferred timezone, which is used for
        streak calculations and UI display.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - timezone
              properties:
                timezone:
                  type: string
                  description: IANA timezone identifier (e.g. Asia/Manila).
      responses:
        '200':
          description: Timezone updated or already set to requested value
        '400':
          description: Missing or invalid timezone value
        '401':
          description: Unauthorized – missing or invalid bearer token
        '404':
          description: Profile not found
  /api/gamification/streak/use-saver:
    post:
      tags:
        - Gamification
      summary: Consume a streak saver
      description: >-
        Uses an available streak saver for the authenticated user, preventing
        their current streak from resetting.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Streak saver consumption result with updated profile snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GamificationUseSaverResponse'
        '401':
          description: Unauthorized – missing or invalid bearer token
        '404':
          description: Profile not found or streak saver unavailable
  /api/learning-materials:
    get:
      tags:
        - Learning Materials
      summary: List learning materials
      description: >-
        Returns learning materials visible to the authenticated user. Results
        include the user's private uploads and public community resources.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: filter
          schema:
            type: string
            enum: [all, my, community, official]
          description: Optional filter preset to control visibility scope.
        - in: query
          name: category
          schema:
            type: string
          description: Optional category slug to narrow results.
        - in: query
          name: search
          schema:
            type: string
          description: Text query applied to title, description, and tags.
      responses:
        '200':
          description: Array of learning materials ordered by newest first
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LearningMaterial'
        '401':
          description: Unauthorized – missing or invalid bearer token
    post:
      tags:
        - Learning Materials
      summary: Upload a learning material
      description: >-
        Upload a PDF, PPT, or PPTX file (max 100 MB) and store its metadata in
        Supabase. Requires bearer authentication. Private uploads return a
        signed download URL.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - title
                - file
              properties:
                title:
                  type: string
                  description: Display name for the material.
                description:
                  type: string
                  nullable: true
                  description: Optional longer summary shown in listings.
                category:
                  type: string
                  nullable: true
                  description: Optional category label.
                tags:
                  type: string
                  nullable: true
                  description: JSON encoded array of tag strings.
                is_public:
                  type: boolean
                  description: Whether the file is visible in the community library.
                file:
                  type: string
                  format: binary
                  description: PDF, PPT, or PPTX document up to 100 MB.
      responses:
        '201':
          description: Created – metadata saved and file stored successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LearningMaterialUploadResponse'
        '400':
          description: Invalid payload or unsupported file
        '401':
          description: Unauthorized – missing or invalid bearer token
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - user_id
        - completed
      properties:
        id:
          type: integer
          example: 42
        title:
          type: string
          example: Finish TypeScript homework
        user_id:
          type: integer
          example: 123
        completed:
          type: boolean
          example: false
    NewTodo:
      type: object
      required:
        - title
        - user_id
      properties:
        title:
          type: string
          example: Finish TypeScript homework
        user_id:
          type: integer
          description: Supabase auth user id associated with the todo
          example: 123
        completed:
          type: boolean
          description: Optional initial completion state (defaults to false)
          example: false
    GamificationProfile:
      type: object
      properties:
        username:
          type: string
          nullable: true
          example: studybuddy
        streak_count:
          type: integer
          nullable: true
          example: 12
          description: Consecutive study days tracked by the system
        total_study_time:
          type: integer
          nullable: true
          example: 540
          description: Total tracked study time in minutes
        level:
          type: integer
          nullable: true
          example: 3
        experience_points:
          type: integer
          nullable: true
          example: 1250
        created_at:
          type: string
          format: date-time
          nullable: true
        streak_longest:
          type: integer
          nullable: true
          example: 25
          description: Longest streak achieved by the user
        streak_last_active_at:
          type: string
          format: date-time
          nullable: true
          description: Timestamp (UTC) when the streak was last activated
        streak_timezone:
          type: string
          nullable: true
          example: Asia/Manila
          description: IANA timezone identifier used for streak calculations
    GamificationStreakActivationRequest:
      type: object
      properties:
        occurred_at:
          type: string
          format: date-time
          description: ISO timestamp for when the study activity ended (defaults to now)
        timezone:
          type: string
          description: Preferred IANA timezone for streak evaluation (defaults to stored timezone or UTC)
          example: Asia/Manila
        study_minutes:
          type: integer
          minimum: 0
          description: Minutes of focused study to add to the cumulative total
          example: 25
        duration_minutes:
          type: integer
          minimum: 0
          description: Alias for study_minutes to maintain backwards compatibility
          example: 25
    GamificationStreakActivationResponse:
      type: object
      required:
        - profile
        - streak_was_incremented
        - streak_was_reset
        - study_minutes_applied
      properties:
        profile:
          $ref: '#/components/schemas/GamificationProfile'
        streak_was_incremented:
          type: boolean
          description: Indicates whether the streak increased by one
        streak_was_reset:
          type: boolean
          description: Indicates whether the streak was reset to 1 due to a lapse
        study_minutes_applied:
          type: integer
          description: Total minutes applied from the request payload (rounded to an integer)
    GamificationUseSaverResponse:
      type: object
      required:
        - success
        - profile
      properties:
        success:
          type: boolean
          description: Indicates whether a streak saver was successfully consumed.
        payload:
          type: object
          nullable: true
          additionalProperties: true
          description: Raw RPC response returned by the Supabase function.
        profile:
          $ref: '#/components/schemas/GamificationProfile'

