openapi: 3.0.3
info:
  title: StudyStreak PHP backend API
  version: "1.0.0"
  description: >-
    Minimal contract for the /api/todos endpoints consumed by the StudyStreak
    frontend.
servers:
  - url: https://studystreak-backend.onrender.com
    description: Production deployment
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/todos:
    get:
      summary: List todos
      description: >-
        Returns a list of todos. Optional `user_id` query parameter filters the
        result set by owner.
      parameters:
        - in: query
          name: user_id
          schema:
            type: integer
          description: Filter todos by owner id
      responses:
        '200':
          description: Successful response containing a JSON array of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized – missing or invalid bearer token
    post:
      summary: Create a todo
      description: >-
        Create a new todo. Requires an `Authorization: Bearer <user_jwt>` header
        with a valid Supabase user JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Created – returns the newly created todo representation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized – missing or invalid bearer token
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - user_id
        - completed
      properties:
        id:
          type: integer
          example: 42
        title:
          type: string
          example: Finish TypeScript homework
        user_id:
          type: integer
          example: 123
        completed:
          type: boolean
          example: false
    NewTodo:
      type: object
      required:
        - title
        - user_id
      properties:
        title:
          type: string
          example: Finish TypeScript homework
        user_id:
          type: integer
          description: Supabase auth user id associated with the todo
          example: 123
        completed:
          type: boolean
          description: Optional initial completion state (defaults to false)
          example: false
