FROM node:18-alpine
RUN npm install -g @upstash/context7-mcp
CMD ["context7-mcp"]


#cd docker
# docker compose build ai-service
# docker run --rm --gpus all -d -p 8000:8000 --name studystreak-ai-run studystreak-ai:latest